apiVersion: v1
kind: Service
metadata:
  name: crdb-embeddings-lb
spec:
  selector:
    app: crdb-embeddings
  ports:
  - protocol: "TCP"
    port: 80 
    targetPort: 18080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crdb-embeddings
spec:
  selector:
    matchLabels:
      app: crdb-embeddings
  replicas: 1
  template:
    metadata:
      labels:
        app: crdb-embeddings
    spec:
      containers:
      - name: crdb-embeddings
        image: mgoddard/crdb-embeddings-x86:1.39
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "3"
            memory: "12Gi"
          limits:
            cpu: "3"
            memory: "12Gi"
        env:
          - name: DB_URL
            value: "postgres://embeduser:embedpasswd@cockroachdb-public:26257/defaultdb"
          - name: N_THREADS
            value: "10"
          - name: LOG_LEVEL
            value: "INFO"
          - name: FLASK_PORT
            value: "18080"
          - name: MAX_RETRIES
            value: "3"
          - name: MIN_SENTENCE_LEN
            value: "12"
          - name: N_CLUSTERS
            value: "1536"
          - name: TRAIN_FRACTION
            value: "0.9"
          - name: MODEL_FILE
            value: "/tmp/model.pkl"
          - name: MODEL_FILE_URL
            value: "https://storage.googleapis.com/crl-goddard-text/model_Fastembed_1536.pkl"
          - name: BATCH_SIZE
            value: "1024"
          - name: KMEANS_VERBOSE
            value: "2"
          - name: KMEANS_MAX_ITER
            value: "100"
          - name: SECRET
            value: "TextWithNoSpecialChars"
          - name: BLOB_STORE_KEEP_N_ROWS
            value: "3"
          - name: SKIP_KMEANS
            value: "false"
          - name: TOKENIZERS_PARALLELISM
            value: "false"
          - name: MEMORY_LIMIT_MB
            value: "4096"
          - name: MAX_CHUNKS
            value: "256"
        ports:
        - containerPort: 18080
        readinessProbe:
          httpGet:
            path: /health
            port: 18080
          initialDelaySeconds: 5
          periodSeconds: 5
      restartPolicy: Always

